- hosts: lamp
  become: yes

  tasks:
   - name: Install Apache2
     apt:
      update_cache: yes
      name: apache2
      state: present
   - name: Installer MariaDB
     apt:
      update_cache: yes
      name: mariadb_server
      state: present
      
   - name: Start Apache2
     service:
      name: apache2
      state: started
      enabled: yes
   - name: Start MariaDB
     service:
      name: mysql
      state: started
      enabled: yes