---
- hosts: lamp
  become: yes
  vars_files: 
    - vars.yml

  handlers: 
  # Action execute when it's notify
    - name: restart apache 
    service: 
      name: apache2
      state: restarted

  pre_tasks: 
    # Instal package
    - name: Update apt cache if needed. 
      apt: 
        update_cache: yes
        cache_valid_time: 3600
    - name: Instal apt-transport-https
      apt:
        name: apt-transport-https
        state: present
    - name: Instal lsb-release
      apt:
        name: lsb-release
        state: present
    - name: Instal ca-certificates
      apt:
        name: ca-certificates
        state: present

  tasks:
    # Add repos
    - name: Add sury repos in php.list file 
      apt_repository: 
        repo: deb https://packages.sury.org/php/ $(lsb_release -sc) main
        state: present 
        filename: 'php'
        register: sury_apt_repo
    - name: Add sury gpg key 
      apt_key: 
        url: "https://packages.sury.org/php/apt.gpg" 
        state: present 
        register: sury_apt_key
    - name: Update apt cache if repo or key added. 
      apt: 
        update_cache: yes
      when: sury_apt_repo.changed or sury_apt_key.changed

    # Instal service
    - name: Instal Apache2
      apt:
        update_cache: yes
        name: apache2
        state: present
    - name: Instal MariaDB
      apt:
        update_cache: yes
        name: mariadb_server
        state: present
    - name: Instal PHP7.2
      apt:
        update_cache: yes
        name: php7.2-cli
        state: present
    
    # Start and enable service
    - name: Start Apache2
      service:
        name: apache2
        state: started
        enabled: yes
    - name: Start MariaDB
      service:
        name: mysql
        state: started
        enabled: yes
    - name: Start PHP7.2
      service:
        name: php7.2-cli
        state: present
        enabled: yes

    # Copy file configuration
    - name: Copy file 
      copy: 
        src: "{{ item.src }}" 
        dest: "{{ item.dest }}" 
        owner: "{{ item.owner }}" 
        group: "{{ item.group }}" 
        mode: 0644
      with_items: 
        - src: "security.conf" 
          dest: "/etc/apache2/conf-available/security.conf" 
          owner: root 
          group: root
        - src: "ports.conf" 
          dest: "/etc/apache2/ports.conf" 
          owner: root 
          group: root
        - src: "index.html" 
          dest: "/var/www/html/index.html" 
          owner: www-data
          group: www-data
        - src: "apache2.conf.j2.conf" 
          dest: "/etc/apache2/sites-available/monsite.conf" 
          owner: root 
          group: root
        - src: "php.conf.j2.conf" 
          dest: "/etc/php/7.2/fpm/pool.d/monsite.conf" 
          owner: root 
          group: root

  post_tasks:
    - name: Activate PHP7 conf 
    command: a2enconf php7.2-fpm
    notify: restart apache