# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.box_url = "https://vagrantcloud.com/debian/stretch64"
  
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 1024, "--cpus", 1]
  end
  
  config.vm.provision "ansible" do |ansible|
	  ansible.compatibility_mode = "2.0"
	  ansible.host_key_checking = false
	  ansible.verbose = "v"
	  ansible.playbook = "playbook.yml"
  end
  
  config.vm.define :lamp, primary: true do |lamp_config|
    lamp_config.vm.hostname = 'lamp'
    lamp_config.vm.network :forwarded_port, guest: 8080, host: 8080
    lamp_config.vm.network :forwarded_port, guest: 80, host: 8081
    lamp_config.vm.network :private_network, ip: "192.168.33.10", netmask: "255.255.255.0"
	lamp_config.vm.provision :shell, :path => "script.sh"
  end
end